# Generated by Django 3.2.13 on 2022-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
